<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="0.000">
  <testcase classname="__main__.qa_diezmaoppenhein" name="test_001_t" time="0.0003">
    <error type="exceptions.TypeError">__init__() takes exactly 3 arguments (2 given)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "qa_diezmaoppenhein.py", line 38, in test_001_t
    prom=diezmaoppenhein(3)
    </error>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
